data("AirPassengers")
print(AirPassengers)
# Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
# 1949 112 118 132 129 121 135 148 148 136 119 104 118
# 1950 115 126 141 135 125 149 170 170 158 133 114 140
# 1951 145 150 178 163 172 178 199 199 184 162 146 166
# 1952 171 180 193 181 183 218 230 242 209 191 172 194
# 1953 196 196 236 235 229 243 264 272 237 211 180 201
# 1954 204 188 235 227 234 264 302 293 259 229 203 229
# 1955 242 233 267 269 270 315 364 347 312 274 237 278
# 1956 284 277 317 313 318 374 413 405 355 306 271 306
# 1957 315 301 356 348 355 422 465 467 404 347 305 336
# 1958 340 318 362 348 363 435 491 505 404 359 310 337
# 1959 360 342 406 396 420 472 548 559 463 407 362 405
# 1960 417 391 419 461 472 535 622 606 508 461 390 432


is.ts(AirPassengers)
# yep it is a TimeSeries data

summary(AirPassengers)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 104.0   180.0   265.5   280.3   360.5   622.0 

start(AirPassengers)
end(AirPassengers)
time(AirPassengers)


ts.plot(AirPassengers, xlab="Year", ylab="Number of Passengers", main="Monthly totals of international airline passengers, 1949-1960")

# This will fit in a line
abline(reg=lm(AirPassengers~time(AirPassengers)))


# Auto Coorelation Function help us determine what type of series we have, 
# whether it is a White noise, Random walk, Auto regressive or Moving average.

acf(AirPassengers)
pacf(AirPassengers)



#Fit the AR model to AirPassengers
#For a given time series x we can fit the autoregressive (AR) model using the arima() 
#command and setting order equal to c(1, 0, 0). 
#Note for reference that an AR model is an ARIMA(p, q, d) model.

#Fitting the AR Model to the time series
AR <- arima(AirPassengers, order = c(1,0,0))
print(AR)


# Call:
#   arima(x = AirPassengers, order = c(1, 0, 0))
# 
# Coefficients:
#   ar1  intercept
# 0.9646   278.4649
# s.e.  0.0214    67.1141
# 
# sigma^2 estimated as 1119:  log likelihood = -711.09,  aic = 1428.18


ts.plot(AirPassengers)
AR_fit <- AirPassengers - residuals(AR)
points(AR_fit, type = "l", col = 2, lty = 2)



#Forcasting using AR model
#The predict() function can be used to make forecasts from an estimated AR model. 
#In the object generated by your predict() command, the $pred value is the forceast, and the $se value is the standard error for the forceast. 
#To make predictions for several periods beyond the last observations, you can use the n.ahead argument in your predict() command. 
#This argument establishes the forecast horizon (h), or the number of periods being forceast. 
#The forecasts are made recursively from 1 to h-steps ahead from the end of the observed time series.

#Using predict() to make a 1-step forecast
predict_AR <- predict(AR)

#Obtaining the 1-step forecast using $pred[1]
predict_AR$pred[1]
# [1] 426.5698
#ALternatively Using predict to make 1-step through 10-step forecasts
predict(AR, n.ahead = 10)
# $`pred`
# Jan      Feb      Mar      Apr      May      Jun      Jul      Aug      Sep      Oct
# 1961 426.5698 421.3316 416.2787 411.4045 406.7027 402.1672 397.7921 393.5717 389.5006 385.5735
# 
# $se
# Jan      Feb      Mar      Apr      May      Jun      Jul      Aug      Sep      Oct
# 1961 33.44577 46.47055 55.92922 63.47710 69.77093 75.15550 79.84042 83.96535 87.62943 90.90636


#plotting the AirPassenger series plus the forecast and 95% prediction intervals
ts.plot(AirPassengers, xlim = c(1949, 1961))
AR_forecast <- predict(AR, n.ahead = 10)$pred
AR_forecast_se <- predict(AR, n.ahead = 10)$se
points(AR_forecast, type = "l", col = 2)
points(AR_forecast - 2*AR_forecast_se, type = "l", col = 2, lty = 2)
points(AR_forecast + 2*AR_forecast_se, type = "l", col = 2, lty = 2)

#############################################################################
#############################################################################
#############################################################################
#############################################################################
#    Fit the MA model to AirPassengers
#        We can fit the simple moving average (MA) model using arima(., order = c(0, 0, 1)). 
#        Note for reference that an MA model is an ARIMA(0, 0, 1) model.

#Fitting the MA model to AirPassengers
MA <- arima(AirPassengers, order = c(0,0,1))
print(MA)

# arima(x = AirPassengers, order = c(0, 0, 1))
# 
# Coefficients:
#   ma1  intercept
# 0.9642   280.6464
# s.e.  0.0214    10.5788
# 
# sigma^2 estimated as 4205:  log likelihood = -806.43,  aic = 1618.86

#plotting the series along with the MA fitted values
ts.plot(AirPassengers)
MA_fit <- AirPassengers - resid(MA)
points(MA_fit, type = "l", col = 2, lty = 2)


#Forcasting using MA model
#Making a 1-step forecast based on MA
predict_MA <- predict(MA)

#Obtaining the 1-step forecast using $pred[1]
predict_MA$pred[1]
# [1] 425.1049

#ALternatively Using predict to make 1-step through 10-step forecasts
predict(MA, n.ahead = 10)
#$`pred`
# Jan      Feb      Mar      Apr      May      Jun      Jul      Aug      Sep      Oct
# 1961 425.1049 280.6464 280.6464 280.6464 280.6464 280.6464 280.6464 280.6464 280.6464 280.6464
# 
# $se
# Jan      Feb      Mar      Apr      May      Jun      Jul      Aug      Sep      Oct
# 1961 64.84895 90.08403 90.08403 90.08403 90.08403 90.08403 90.08403 90.08403 90.08403 90.08403

#Plotting the AIrPAssenger series plus the forecast and 95% prediction intervals
ts.plot(AirPassengers, xlim = c(1949, 1961))
MA_forecasts <- predict(MA, n.ahead = 10)$pred
MA_forecast_se <- predict(MA, n.ahead = 10)$se
points(MA_forecasts, type = "l", col = 2)
points(MA_forecasts - 2*MA_forecast_se, type = "l", col = 2, lty = 2)
points(MA_forecasts + 2*MA_forecast_se, type = "l", col = 2, lty = 2)


#Choosing AR or MA   Goodness of fit

cor(AR_fit, MA_fit)
#[1] 0.954995

# Find AIC of AR
AIC(AR)
## [1] 1428.179
# Find AIC of MA
AIC(MA)
## [1] 1618.863
# Find BIC of AR
BIC(AR)
## [1] 1437.089
# Find BIC of MA
BIC(MA)
## [1] 1627.772

#Given the lower value of AIC and BIC in AR model, 
#we should go with that for the time series analysis of AirPassenger data.


library(forecast)
AutoArimaModel=auto.arima(AirPassengers)
AutoArimaModel

# Series: AirPassengers 
# ARIMA(2,1,1)(0,1,0)[12] 
# 
# Coefficients:
#   ar1     ar2      ma1
# 0.5960  0.2143  -0.9819
# s.e.  0.0888  0.0880   0.0292
# 
# sigma^2 estimated as 132.3:  log likelihood=-504.92
# AIC=1017.85   AICc=1018.17   BIC=1029.35



#This function actually searches for a range of p, q values, after fixing d by Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test. 
#It chooses the model having lowest AIC score.

